CoreAndFood/Controllers/FoodController.cs
using CoreAndFood.Data.Models;
using CoreAndFood.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace CoreAndFood.Controllers
{
    public class FoodController : Controller
    {
        FoodRepository foodRepository = new FoodRepository();
        Context c = new Context();
        public IActionResult Index(int page = 1)
        {
            
            return View(foodRepository.TList("Category").ToPagedList(page,3));
        }
        [HttpGet]
        public IActionResult AddFood()
        {
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }
                                           ).ToList();
            ViewBag.v1 = values;
            return View();

        }
        [HttpPost]
        public IActionResult AddFood(urunekle p)
        {
            Food f = new Food();
            
            if (p.ImageURL != null)
            {
                var extension = Path.GetExtension(p.ImageURL.FileName);
                var newimagename = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/resimler/",newimagename);
                var stream = new FileStream(location, FileMode.Create);
                p.ImageURL.CopyTo(stream);
                f.ImageURL = newimagename;
            }
            f.Name = p.Name;
            f.price = p.price;
            f.Stock = p.Stock;
            f.CategoryID = p.CategoryID;
            //f.Description = p.Description;

            foodRepository.TAdd(f);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteFood(int id)
        {
            foodRepository.TDelete(new Food {FoodID=id});
            return RedirectToAction("Index");
        }
        public IActionResult FoodGet(int id)
        {
            var x = foodRepository.TGet(id);
            List<SelectListItem> values = (from y in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.CategoryName,
                                               Value = y.CategoryID.ToString()
                                           }
                                           ).ToList();
            ViewBag.v1 = values;
            Food f = new Food()
            {
                FoodID=x.FoodID,
                CategoryID = x.CategoryID,
                Name = x.Name,
                price=x.price,
                Stock=x.Stock,
                Description=x.Description,
                ImageURL=x.ImageURL,
            };
            return View(f);
        }
        [HttpPost]
        public IActionResult FoodUpdate(Food p)
        {
            var x = foodRepository.TGet(p.FoodID);
            x.Name = p.Name;
            x.Stock = p.Stock;
            x.price = p.price;
            x.ImageURL = p.ImageURL;
            x.Description = p.Description;
            x.CategoryID = p.CategoryID;
            foodRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
    }
}

CoreAndFood/Views/Food/AddFood.cshtml
@model CoreAndFood.Data.Models.urunekle
@{
    ViewData["Title"] = "AddFood";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Add Page</h2>

<br />
<form class="form group" action="AddFood" asp-controller="Food" method="post" enctype="multipart/form-data">
    @Html.Label("Food Name")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    @Html.Label("Stock")
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    <br />
    @Html.Label("Price")
    @Html.TextBoxFor(x => x.price, new { @class = "form-control" })
    <br />
    @Html.Label("Choose Image")
   
    <input type="file" name="ImageURL" />
    <br />
    @Html.Label("Category")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
    <br />

    <br />
    <button class=" btn btn-primary">Save</button>
</form>

CoreAndFood/Views/Food/FoodGet.cshtml
@model CoreAndFood.Data.Models.Food
@{
    ViewData["Title"] = "FoodGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Add Page</h2>

<br />
@using (Html.BeginForm("FoodUpdate", "Food", FormMethod.Post))
{
    @Html.Label("Food ID")
    @Html.TextBoxFor(x => x.FoodID, new { @class = "form-control" })
    <br />

    @Html.Label("Food Name")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    @Html.Label("Stock")
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    <br />
    @Html.Label("Price")
    @Html.TextBoxFor(x => x.price, new { @class = "form-control" })
    <br />
    @Html.Label("Image URL")
    @Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control" })
    <br />
    @Html.Label("Category")
    @*@Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
    <br />
    @Html.Label("Description")
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    <br />
    <button class=" btn btn-primary">Save</button>

}

CoreAndFood/Views/Food/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core

@model IPagedList<CoreAndFood.Data.Models.Food>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food List</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Food Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Category Name</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Details</th>
    </tr>
    @foreach (var x in Model)
    {


        <tr>
            <th> @x.FoodID</th>
            <td> @x.Name</td>
            <td> @x.price</td>
            <td> @x.Stock</td>
            <td> @x.Category.CategoryName</td>
            <td></td>
            <td> <a href="/Food/DeleteFood/@x.FoodID" class= "btn btn-danger">Delete </a>
            <td> <a href="/Food/FoodGet/@x.FoodID" class="btn btn-success">Update </a>
            <td> <a href="#" class="btn btn-info">Details</a>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model,page =>Url.Action("Index",new {page}))
<a href="/Food/AddFood/" class="  btn btn - primary">New Food </a>