CoreAndFood/Controllers/ChartController.cs
using CoreAndFood.Data;
using CoreAndFood.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreAndFood.Controllers
{
    [AllowAnonymous]
    public class ChartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index2()
        {
            return View();
        }

        public IActionResult VisualizeProductResult()
        {
            return Json(ProList());

        }
        public List<Class1> ProList()
        {
            List<Class1> cs = new List<Class1>();
            cs.Add(new Class1()
            {
                proname = "Computer",
                stock = 200
            });
            cs.Add(new Class1()
            {
                proname = "Samsung",
                stock = 90
            });
            cs.Add(new Class1()
            {
                proname = "USB",
                stock = 250
            });
            return cs;
        }
        public IActionResult Index3()
        {
            return View();
        }
        public IActionResult VisualizeProductResult2()
        {
            return Json(FoodList());
        }
        public List<Class2> FoodList()
        {
            List<Class2> cs2 = new List<Class2>();
            using (var c=new Context())
            {
                cs2 = c.Foods.Select(x => new Class2
                {

                    foodname = x.Name,
                    stock = x.Stock

                }).ToList();
            }
            return cs2;
        }
        public IActionResult Statistics()
        {
            Context c = new Context();
            var deger1 = c.Foods.Count();
            ViewBag.d1 = deger1;

            var deger2 = c.Categories.Count();
            ViewBag.d2 = deger2;

            var foid = c.Categories.Where(x => x.CategoryName == "Fruit").Select(y => y.CategoryID).FirstOrDefault();
            ViewBag.d = foid;

            var deger3 = c.Foods.Where(x=>x.CategoryID==foid).Count();
            ViewBag.d3 = deger3;

            var deger4 = c.Foods.Where(x=>x.CategoryID==c.Categories.Where(z => z.CategoryName == "Vegetables").Select(y => y.CategoryID).FirstOrDefault()).
            
Count();
            ViewBag.d4 = deger4;

            var deger5 = c.Foods.Sum(x=>x.Stock);
            ViewBag.d5 = deger5;


            var deger6 = c.Foods.Where(x => x.CategoryID == c.Categories.Where(y => y.CategoryName == "Legumes").Select(z => z.CategoryID).FirstOrDefault()).

Count();
            ViewBag.d6 = deger6;

            return View();
        }
    } }

CoreAndFood/Views/Chart/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.proname, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Food- Stock Grafic",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

CoreAndFood/Views/Chart/Index2.cshtml
@{
    ViewData["Title"] = "Index2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.proname, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Food-Stock Grafic",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('columnChart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnChart_div"></div>
</body>
</html>

CoreAndFood/Views/Chart/Index3.cshtml
@{
    ViewData["Title"] = "Index3";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult2", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.foodname, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Food - Stock Dynamic Chart",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

CoreAndFood/Views/Chart/Statistics.cshtml
@{
    ViewData["Title"] = "Statistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{ ViewData["Title"] = "Deneme";
                Layout = "~/Views/Shared/_Layout.cshtml"; }


<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link href="~/web2/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Total Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Total Category</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.d3</h3>
                    <p>Number of Fruits</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.d4</h3>
                    <p>Number of Vegetables</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.d5</h3>
                    <p>Total Stock</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Sum of Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Number of Legumes</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3>@ViewBag.d</h3>
                    <p>Max Category Stock</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    
    
    
    
    
    
    
    
    

    
    
    
    
    
    
    

    
    
    
    
    
    
    

    
    
    
    
    
    
    
    
    
</body>
</html>